/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{js,ts,jsx,tsx}"],
	darkMode: "class",
	safelist: [
		"bg-grass",
		"bg-stone",
		"bg-fire",
		"bg-water",
		"bg-sand",
		"bg-dark",
		"bg-dungeon",
	],
	theme: {
		extend: {
			colors: {
				twitchpurple: "rgb(130, 5, 180)",
				discordblurple: "#5865F2",
				"on-tertiary-fixed-variant": "#574500",
				"on-secondary-fixed": "#28180d",
				"surface-tint": "#b5cdaf",
				"on-background": "#e5e2e1",
				"secondary-fixed-dim": "#dec1af",
				"surface-variant": "#353535",
				"on-primary": "#213520",
				"outline-variant": "#434841",
				"on-error": "#690005",
				"surface-bright": "#393939",
				"on-error-container": "#ffdad6",
				error: "#ffb4ab",
				"tertiary-container": "#cca830",
				"surface-container-high": "#2a2a2a",
				"surface-container-highest": "#353535",
				"secondary-container": "#574335",
				"inverse-primary": "#4e644b",
				"primary-fixed-dim": "#b5cdaf",
				"inverse-surface": "#e5e2e1",
				"surface-container-lowest": "#0e0e0e",
				"secondary-fixed": "#fbddca",
				"on-surface": "#e5e2e1",
				"on-tertiary-fixed": "#241a00",
				"on-tertiary-container": "#4f3e00",
				"on-secondary-fixed-variant": "#574335",
				"primary-fixed": "#d0eaca",
				"on-surface-variant": "#c3c8bf",
				"tertiary-fixed-dim": "#e9c349",
				"surface-container-low": "#1c1b1b",
				"surface-dim": "#131313",
				background: "#131313",
				"on-primary-container": "#788f74",
				"tertiary-fixed": "#ffe088",
				"surface-container": "#20201f",
				primary: "#b5cdaf",
				tertiary: "#eac34a",
				"on-primary-fixed-variant": "#374c35",
				"on-primary-fixed": "#0c200c",
				"on-secondary": "#3f2c20",
				"on-secondary-container": "#ccb09f",
				outline: "#8d928a",
				surface: "#131313",
			},
			fontFamily: {
				heading: ["Crete Round", "Georgia", "Times", "serif"],
				sans: ["Lato", "Helvetica", "Arial", "sans"],
				"label-caps": ["Manrope", "sans-serif"],
				"body-lg": ["Manrope", "sans-serif"],
				h2: ["Noto Serif", "serif"],
				"body-md": ["Manrope", "sans-serif"],
				h1: ["Noto Serif", "serif"],
				"stat-num": ["Manrope", "sans-serif"],
			},
			fontSize: {
				"label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
				"body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
				h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
				"body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
				h1: ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
				"stat-num": ["14px", { lineHeight: "1", fontWeight: "600" }],
			},
			borderRadius: {
				DEFAULT: "0.25rem",
				lg: "0.5rem",
				xl: "0.75rem",
				full: "9999px",
			},
			spacing: {
				sm: "16px",
				xs: "8px",
				base: "4px",
				xl: "48px",
				md: "24px",
				lg: "32px",
			},
		},
	},
	plugins: [],
};
